### ISSUE TITLE
VB-16: Add endpoint for creating request and beneficiary at the same time

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#105]
when a request from a new beneficiary is created we need to create both, the request and the beneficiary at the same time.

POST /api/requests
Media type: Application/json

RequestBody(required): Request object as json

Responses:
201: Request object created
Example value:
```
{
//beneficiary data
  "first_name": "string",
  "last_name": "string",
  "phone": "string",
  "landline": "string",
  "age": 0,
  "zone": "botanica",
  "address": "string",
  "special_condition": "disability",
   "created_at": "2020-10-05T07:25:52.900Z"
//request data
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

update also the [swagger json](http://185.181.229.182:5000/swagger/)

**Comment by RomanCudreavtev** [comment]
Assign on me.

**Comment by johnsmithm** [comment]
any updates? we need it in order to move forward on the frontend

**Comment by johnsmithm** [comment]
@RomanCudreavtev ?

**Comment by johnsmithm** [comment]
@RomanCudreavtev any updates? we will re-assign this task in two days @alexciornii
