### ISSUE TITLE
VB-18 Add endpoint to add requests  to a cluster/volunteer

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#107]
The user must be able to add a list of requests to a volunteer.
The request model will be updated with the the cluster_id.

POST /api/clusters
Media type: Application/json

RequestBody(required): cluster object as json

Responses:
201: Cluster object created
Example value:
```
{
  "volunteer": "volunteer_id",
  "request_list": ['request_id_1', 'request_id_2', ....],
  "created_at":  "2020-09-10T21:31:16.741Z"
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

**Comment by serghei-rubailo** [comment]
Hi! 
If no one starts working on this task, I would like to take it.
Thank you!
