### ISSUE TITLE
VB 23 add endpoint to get the notification

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#120]
add a GET endpoint /api/notification/filters/1/5, same as for volunteers and requests.

filter for the properties: status and user

**Comment by serghei-rubailo** [comment]
Hi!
I will take this issue. Thank you!

**Comment by serghei-rubailo** [comment]
Could you please help me with a question.
When a notification should be assigned to a user?
As I see there are no endpoints to fill NotificationUser table.
Should notification be assigned to user who created Beneficiary Request when Notification is created?
Or there will be some other logic?
Thank you!

**Comment by johnsmithm** [comment]
the notification is created when a request is created or canceled, and the notification is assigned to all users.

**Comment by serghei-rubailo** [comment]
Issue can be closed.
