### ISSUE TITLE
Import volunteers from csv file

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#126]
https://www.figma.com/proto/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=585%3A4930&scaling=min-zoom

**Comment by boombasteek** [comment]
This one on me please.

**Comment by johnsmithm** [comment]
@boombasteek any updates?

**Comment by boombasteek** [comment]
> @boombasteek any updates?

Hi, was ill for a period. I'll try to provide solution asap.

**Comment by boombasteek** [comment]
Made v1 pull request, please check.

**Comment by johnsmithm** [comment]
make a PR please

**Comment by boombasteek** [comment]
> make a PR please

Hi, already did.

**Comment by johnsmithm** [comment]
where? PR means to be  a Pull Request in the https://github.com/code4moldova/voluntar-backend repository.
here is the [link](https://github.com/code4moldova/voluntar-backend/pulls) with all PR @boombasteek

**Comment by johnsmithm** [comment]
also add an example of csv, to see how you have tested it

**Comment by boombasteek** [comment]
Hi Ion,
made the PR as requested officially :). Later on will put the example of csv file.

**Comment by johnsmithm** [comment]
@boombasteek any updates? why you deleted the PR?
