### ISSUE TITLE
Add endpoint to get requests by cluster_id for anonymous users 

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#148]
Volunteers must be able to access the list of requests without authentication, and by having the cluster_id

GET /api/requests/list?cluster_id=ddfsdfsd

return same as /api/requests/filters/1/5?cluster_id==dasdasd but without authentication and just based on cluster_id

**Comment by iamandrewluca** [comment]
I think first we should make a endpoint that will return the requests as a list without a cluster.
From what I see in the backend and frontend we don't have one
And benceficiary list was misunderstood and used as a request list. I'll take a look into creating a simple GET /requests

**Comment by johnsmithm** [comment]
what do you mean without a cluster? cluster not to be included in the list item properties or, cluster_id not to be used as a parameter in the request?
