### ISSUE TITLE
Add `is_active` query flag for users list

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/voluntar-backend#157]
In Figma, users list have 3 tabs, `Activi`, `Inavtivi`, `Toti`
We need to use `User` document, `is_active` flag for this.

From frontend we will send `is_active` flag in URL query

e.g.

```http
# should return all
GET /api/operator
# should return only not active
GET /api/operator?is_active=false
# should return only active
GET /api/operator?is_active=true
```

I tried an atempt in commit https://github.com/code4moldova/voluntar-backend/commit/4f8821c431c88f557bbc225e3af7f871a247675a but it seems something is not working right.

**Figma:** https://www.figma.com/proto/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=585%3A5544&scaling=min-zoom&hide-ui=1

**Comment by johnsmithm** [comment]
done here https://github.com/code4moldova/voluntar-backend/pull/156
also functionality exits here http://localhost:5000/api/operator/filters/1/5?is_active=false
