### ISSUE TITLE
VB-4: Add beneficiary filters

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#87]
Add filter by:
- zone
- is_active

**Comment by serghei-rubailo** [comment]
Hello!
Could you please provide more information about the task.
How should filter works? I mean should it works as filter for Volunteers as it was mentioned in #85 (first name OR last name OR phone) AND zone?
Can Beneficiary model be modified according to Class Diagram (phone is StringField)?

**Comment by alexciornii** [comment]
@serghei-rubailo 
Yes, it should works as filters in #85 with difference (first name OR last name OR phone) AND zone AND is_active
See [prototype](https://www.figma.com/proto/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=820%3A1266&viewport=402%2C967%2C0.4029495418071747&scaling=scale-down-width)
Sure, you can modify phone to StringField
