### ISSUE TITLE
VB-6: Update Beneficiary model

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#89]
1. Beneficiary model should extends `Document` directly.
2. Add enums associated with the volunteer model:
```
    SpecialCondition:
        - disability
        - deaf_mute
        - blind_weak_seer
```
3. Add new fields for Beneficiary model:
- first_name
- last_name
- phone
- landline
- created_at

Fields that are not mentioned should be moved at the end of Beneficiary model and marked as deprecated.

**Comment by RomanCudreavtev** [comment]
Please asign on me
