### ISSUE TITLE
VB-12: filter the requests based on first, last name and phone/landline

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#95]
GET /api/requests
Media type: Application/json

Description:
Method should filter returned records by query parameters.

Query parameters:
- page
    default: 0
- page_size
    default: 30
- first_name
- last_name
- phone
- zone
- created_at

Responses:
200: An array of request objects
Example value:
```
{
"metadata": {
"page": "0",
"page_size": "30",
"page_count":  "5",
"total_count": "100"
},
"records":
[
{
  "id": "1"
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
},
{
  "id": "2"
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
}
]
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

**Comment by vitaliel** [comment]
It is implemented partially, I added filter by beneficiary that I needed: https://github.com/code4moldova/voluntar-backend/pull/109/files#diff-8dda545adfe164bd508bc74b27809a753ea03f63022dc3e307f15d98b2e0eb45R6

**Comment by johnsmithm** [comment]
this one could be a bit more complicated than the other filters, because we will need to filter the beneficiary by name, phone, etc, then find the request for these people

**Comment by johnsmithm** [comment]
@vitaliel  @alexciornii any ideas of how to filter the request based on beneficiary name and phone?

**Comment by serghei-rubailo** [comment]
Hello!
Please check pull request #139, I tried to implement search requests by Beneficiaries parameters. But please note, I implemented exact match search.
