### ISSUE TITLE
VB-13: Add new endpoint to get a request by ID

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#96]
GET /api/requests/{request_id}
Media type: Application/json

Path parameters:
- request_id

Responses:
200: Request object found
Example value:
```
{
  "id": "1",
  "beneficiary": "beneficiary_id",
  "user": "user_id",
  "status": "new",
  "secret": "string",
  "urgent": false,
  "comments": "string",
  "has_symptoms": false,
  "cluster": "cluster_id",
  "created_at": "2020-09-10T21:31:16.741Z"
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

**Comment by RomanCudreavtev** [comment]
Please sign on me.

**Comment by johnsmithm** [comment]
i added the functionality in the endpoint` /api/request/filters/1/5?id=aasdadadsa` in #115 , I think it is enough. @alexciornii what do you think?
