### ISSUE TITLE
VB-15: Add endpoint for creating a new Notification

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#98]
POST /api/notifications
Media type: Application/json

RequestBody(required): Notification object as json

Responses:
201: Notification object created
Example value:
```
{
  "request": "request_id",
  "type": "new_request",
  "subject": "string",
  "created_at": "2020-09-10T21:31:16.741Z"
}
```
400: Bad request
Example value:
```
{
  "code": "string",
  "message": "string"
}
```
401: Unauthorized Access
Example value:
`Unauthorized Access`

**Comment by serghei-rubailo** [comment]
Hi! If the issues is not already taken, I would like to implement it.
Thank you!
